# Generated by Django 5.2.7 on 2025-10-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixModel',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubstanceModel',
            fields=[
                ('CAS', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=10)),
                ('group', models.CharField(choices=[('PFAS', 'PFAS'), ('iPMT', 'iPM(T)'), ('Pharmaceutical', 'Pharmaceutical')])),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentModel',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('group', models.CharField(choices=[('DWT', 'Drinking Water'), ('GWT', 'Groundwater'), ('WWT', 'Wastewater'), ('NAP', 'Natural Process'), ('MIX', 'Mixing and Separation')])),
                ('input_matrix', models.ManyToManyField(related_name='input_to_treatments', to='qcra.matrixmodel')),
                ('output_matrix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qcra.matrixmodel')),
            ],
        ),
    ]
