# Generated by Django 5.2.7 on 2026-01-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentmodel',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
