# Generated by Django 5.2.7 on 2026-01-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcra', '0002_alter_treatmentmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value_ng_l', models.FloatField()),
                ('year', models.IntegerField()),
                ('comments', models.TextField()),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcra.matrixmodel')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcra.substancemodel')),
            ],
        ),
    ]
