# Generated by Django 5.2.7 on 2026-01-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcra', '0003_referencemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencemodel',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencemodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
