# Generated by Django 5.2.7 on 2026-01-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcra', '0004_alter_referencemodel_comments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferenceModel',
            new_name='ReferenceConcentrationModel',
        ),
        migrations.CreateModel(
            name='RemovalReferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('removal_percent', models.IntegerField()),
                ('DOI', models.CharField(max_length=64, null=True)),
                ('year', models.IntegerField(null=True)),
                ('figure', models.CharField(max_length=64, null=True)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcra.substancemodel')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcra.treatmentmodel')),
            ],
        ),
    ]
